# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JdJqC8Cj3BvvXZwhiNakIBl6e7BSL45J3eAGxSebtPC5xmVOWHrGQnenDZhLXVFvsw13blkgvVZSwx0B1bUqqW8UosLbNNvXTekuQBM00xPh38UN8LTP9PO1Ir+xDi8Ow4S2BX8hHjWsKsEoD3xKxOWA83EEnRMKNUtKElf9JTywrreRxYItRNb/XF+APWmxO292BtCxXsl8AHnthwE35ejaS/xT43cPRj2THWBne5VT9DTTTUR9HYJBQdi4WsmmdrVQUQ1+TnmDxSHScTfoMma4oKFDuT9K4hO2hZnpJmC4pTGfZfDZXsKl0YhhJM6OSwx8j/aUAipFBby4xTUjTph1eP9P1+q7WbgBgvB39qzlp70UnFOpcIGNSLICm/NTdNxo0P0HVfnaKfGC0jzfRC79PbPsKoyED25j8b8TIff1bkujwlpb3re3UDUW/tLLZLF0+JZWYz+FHfwxrSFtQXm2I9RPi9Ql+DsWqTkrp/TYii8JKse7cijytlegZlQ9AwFlP+ZVteir/GAOe2N7NjPxYmcBthbxFRvO31sGmszrwMr5q9I2m9qpOSxGXUGmX5wbwx61a8YnXOl+cpFYfcEwNj8B03X5XLQqU4y2KHOSYS26IFvJ450bz2keGvL1j3OOrJI0JEtX9k+ZmaTaqn19gzUrEUZMks3GVic5o34="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
