appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: JdJqC8Cj3BvvXZwhiNakIBl6e7BSL45J3eAGxSebtPC5xmVOWHrGQnenDZhLXVFvsw13blkgvVZSwx0B1bUqqW8UosLbNNvXTekuQBM00xPh38UN8LTP9PO1Ir+xDi8Ow4S2BX8hHjWsKsEoD3xKxOWA83EEnRMKNUtKElf9JTywrreRxYItRNb/XF+APWmxO292BtCxXsl8AHnthwE35ejaS/xT43cPRj2THWBne5VT9DTTTUR9HYJBQdi4WsmmdrVQUQ1+TnmDxSHScTfoMma4oKFDuT9K4hO2hZnpJmC4pTGfZfDZXsKl0YhhJM6OSwx8j/aUAipFBby4xTUjTph1eP9P1+q7WbgBgvB39qzlp70UnFOpcIGNSLICm/NTdNxo0P0HVfnaKfGC0jzfRC79PbPsKoyED25j8b8TIff1bkujwlpb3re3UDUW/tLLZLF0+JZWYz+FHfwxrSFtQXm2I9RPi9Ql+DsWqTkrp/TYii8JKse7cijytlegZlQ9AwFlP+ZVteir/GAOe2N7NjPxYmcBthbxFRvO31sGmszrwMr5q9I2m9qpOSxGXUGmX5wbwx61a8YnXOl+cpFYfcEwNj8B03X5XLQqU4y2KHOSYS26IFvJ450bz2keGvL1j3OOrJI0JEtX9k+ZmaTaqn19gzUrEUZMks3GVic5o34=}
bot:
  automerge: true
